### ISSUE TITLE
Win 7 - It trys to open the .exe before scanning..

### ISSUE THREAD

**Issue by H8DCarnifeX** [Genbox/VirusTotalContextMenu#3]
Isnt it the exact opposite somebody wanna do, open the .exe which could be suspicious?

**Comment by Genbox** [comment]
It does not open the executable. If you are seeing a dialog, it is probably because Windows SmartScreen (or similar) thinks the context menu exe is suspicious. It often happens when downloading an exe directly form the internet - I can package the exe in a zip file, which will make the warning go away.
